import BC4lean.AdjointableComplete
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.LinearAlgebra.Quotient.Basic

/-! # The algebraic balanced tensor of Hilbert C⋆-modules

Mathlib's `TensorProduct` is over commutative scalars.  We therefore take the
genuine complex tensor product and quotient by the complex span of the
coefficient-balancing relations.  This works for noncommutative, possibly
nonunital coefficient algebras and for degenerate left representations.

This file constructs an algebraic complex module and its universal map.  No
positivity, norm, Hilbert-module structure, or completion is asserted here.
-/

noncomputable section
namespace BC4lean.KKTheory

open scoped TensorProduct

variable {B C E F : Type*} [NonUnitalCStarAlgebra B] [NonUnitalCStarAlgebra C]
  [PartialOrder C]
  [NormedAddCommGroup E] [NormedSpace ℂ E] [SMul Bᵐᵒᵖ E]
  [NormedAddCommGroup F] [NormedSpace ℂ F] [SMul Cᵐᵒᵖ F] [CStarModule Cᵐᵒᵖ F]

/-- The complex span of the genuine coefficient-balancing relations. -/
def moduleTensorRelations (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) :
    Submodule ℂ (E ⊗[ℂ] F) :=
  Submodule.span ℂ (Set.range fun t : B × E × F =>
    (MulOpposite.op t.1 • t.2.1) ⊗ₜ[ℂ] t.2.2 - t.2.1 ⊗ₜ[ℂ] (φ t.1 t.2.2))

/-- The algebraic balanced tensor, before quotienting by null vectors or
completing. -/
abbrev BalancedModuleTensor (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) :=
  (E ⊗[ℂ] F) ⧸ moduleTensorRelations (E := E) φ

/-- The canonical bilinear map to the algebraic balanced tensor. -/
def moduleTensorMk (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) :
    E →ₗ[ℂ] F →ₗ[ℂ] BalancedModuleTensor (E := E) φ :=
  (TensorProduct.mk ℂ E F).compr₂ (moduleTensorRelations (E := E) φ).mkQ

@[simp] theorem moduleTensorMk_apply (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (x : E) (y : F) :
    moduleTensorMk φ x y =
      (moduleTensorRelations (E := E) φ).mkQ (x ⊗ₜ[ℂ] y) := rfl

/-- The balancing relation is an actual equality in the constructed quotient. -/
theorem moduleTensorMk_balance (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (b : B) (x : E) (y : F) :
    moduleTensorMk φ (MulOpposite.op b • x) y = moduleTensorMk φ x (φ b y) := by
  apply sub_eq_zero.mp
  change (moduleTensorRelations (E := E) φ).mkQ ((MulOpposite.op b • x) ⊗ₜ[ℂ] y) -
    (moduleTensorRelations (E := E) φ).mkQ (x ⊗ₜ[ℂ] (φ b y)) = 0
  rw [← map_sub]
  apply (Submodule.Quotient.mk_eq_zero _).mpr
  exact Submodule.subset_span ⟨(b, x, y), rfl⟩

variable {P : Type*} [AddCommGroup P] [Module ℂ P]

/-- A balanced bilinear map annihilates the defining relation submodule. -/
theorem moduleTensorRelations_le_ker (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (f : E →ₗ[ℂ] F →ₗ[ℂ] P)
    (hf : ∀ (b : B) (x : E) (y : F), f (MulOpposite.op b • x) y = f x (φ b y)) :
    moduleTensorRelations (E := E) φ ≤ LinearMap.ker (TensorProduct.lift f) := by
  apply Submodule.span_le.mpr
  rintro _ ⟨⟨b, x, y⟩, rfl⟩
  change TensorProduct.lift f
    ((MulOpposite.op b • x) ⊗ₜ[ℂ] y - x ⊗ₜ[ℂ] (φ b y)) = 0
  simp only [map_sub, TensorProduct.lift.tmul, hf, sub_self]

/-- The genuine universal lift from the balanced tensor quotient. -/
def moduleTensorLift (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (f : E →ₗ[ℂ] F →ₗ[ℂ] P)
    (hf : ∀ (b : B) (x : E) (y : F), f (MulOpposite.op b • x) y = f x (φ b y)) :
    BalancedModuleTensor (E := E) φ →ₗ[ℂ] P :=
  (moduleTensorRelations (E := E) φ).liftQ (TensorProduct.lift f)
    (moduleTensorRelations_le_ker φ f hf)

@[simp] theorem moduleTensorLift_apply (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (f : E →ₗ[ℂ] F →ₗ[ℂ] P)
    (hf : ∀ (b : B) (x : E) (y : F), f (MulOpposite.op b • x) y = f x (φ b y))
    (x : E) (y : F) : moduleTensorLift φ f hf (moduleTensorMk φ x y) = f x y := rfl

/-- A linear map from the balanced tensor is determined by its values on
elementary tensors. -/
theorem moduleTensor_ext (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    {f g : BalancedModuleTensor (E := E) φ →ₗ[ℂ] P}
    (h : ∀ x y, f (moduleTensorMk φ x y) = g (moduleTensorMk φ x y)) : f = g := by
  apply Submodule.linearMap_qext
  apply TensorProduct.ext'
  exact h

/-- Uniqueness in the universal property of the constructed balanced tensor. -/
theorem moduleTensorLift_unique (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (f : E →ₗ[ℂ] F →ₗ[ℂ] P)
    (hf : ∀ (b : B) (x : E) (y : F), f (MulOpposite.op b • x) y = f x (φ b y))
    (g : BalancedModuleTensor (E := E) φ →ₗ[ℂ] P)
    (hg : ∀ x y, g (moduleTensorMk φ x y) = f x y) :
    g = moduleTensorLift φ f hf := by
  apply moduleTensor_ext φ
  intro x y
  exact hg x y

/-- The constructed quotient is generated by elementary tensors. -/
@[elab_as_elim] theorem moduleTensor_induction
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    {p : BalancedModuleTensor (E := E) φ → Prop} (z : BalancedModuleTensor (E := E) φ)
    (h0 : p 0) (hθ : ∀ x y, p (moduleTensorMk φ x y))
    (hadd : ∀ u v, p u → p v → p (u + v)) : p z := by
  induction z using Submodule.Quotient.induction_on with
  | H z =>
    induction z using TensorProduct.induction_on with
    | zero => exact h0
    | tmul x y => exact hθ x y
    | add u v hu hv => exact hadd _ _ hu hv

end BC4lean.KKTheory
