import BC4lean.LabeledOrbitExhaustion
import BC4lean.LabeledOrbitRealizationProper
import Mathlib.Topology.Algebra.ProperAction.CompactlyGenerated

noncomputable section
open scoped Pointwise
namespace BC4lean.ProperActions.LabeledOrbitRealization
variable {Γ : Type*} [Group Γ]

/-- Realization of the faces generated by finitely many simplex orbits. -/
def OrbitFaceSpace (F : Finset (LabeledOrbitSimplex Γ)) :=
  {x : LabeledOrbitRealization Γ // supportSimplex x ∈ LabeledOrbitSimplex.orbitFaces F}

instance (F : Finset (LabeledOrbitSimplex Γ)) : TopologicalSpace (OrbitFaceSpace F) :=
  inferInstanceAs (TopologicalSpace {x : LabeledOrbitRealization Γ //
    supportSimplex x ∈ LabeledOrbitSimplex.orbitFaces F})

instance (F : Finset (LabeledOrbitSimplex Γ)) : T2Space (OrbitFaceSpace F) :=
  .of_injective_continuous Subtype.val_injective continuous_subtype_val

theorem support_chart_subset (s : LabeledOrbitSimplex Γ)
    (w : LabeledSimplexCoordinates Γ s) :
    (supportSimplex (chart s w)).vertices ⊆ s.vertices := by
  intro v hv
  have hn := (mem_supportSimplex (chart s w) v).mp hv
  by_contra h
  exact hn (w.property.2.1 v h)

/-- Every allowed finite chart maps continuously into the generated subspace. -/
def orbitFaceChart {F : Finset (LabeledOrbitSimplex Γ)}
    (s : LabeledOrbitSimplex Γ) (hs : s ∈ LabeledOrbitSimplex.orbitFaces F)
    (w : LabeledSimplexCoordinates Γ s) : OrbitFaceSpace F :=
  ⟨chart s w, LabeledOrbitSimplex.orbitFaces_downward hs (support_chart_subset s w)⟩

theorem continuous_orbitFaceChart {F : Finset (LabeledOrbitSimplex Γ)}
    (s : LabeledOrbitSimplex Γ) (hs : s ∈ LabeledOrbitSimplex.orbitFaces F) :
    Continuous (orbitFaceChart s hs) :=
  (continuous_chart s).subtype_mk _

theorem isCompact_range_orbitFaceChart {F : Finset (LabeledOrbitSimplex Γ)}
    (s : LabeledOrbitSimplex Γ) (hs : s ∈ LabeledOrbitSimplex.orbitFaces F) :
    IsCompact (Set.range (orbitFaceChart s hs)) :=
  isCompact_range (continuous_orbitFaceChart s hs)

/-- Only finitely many translated generating charts contain a specified vertex. -/
theorem finite_translated_charts_containing (F : Finset (LabeledOrbitSimplex Γ))
    (v : LabeledOrbitVertex Γ) :
    ({t : LabeledOrbitSimplex Γ | v ∈ t.vertices ∧ ∃ s ∈ F, ∃ g : Γ, g • s = t}).Finite := by
  classical
  have hf : (⋃ s ∈ (F : Set (LabeledOrbitSimplex Γ)),
      ⋃ w ∈ (s.vertices : Set (LabeledOrbitVertex Γ)),
        (fun g : Γ => g • s) '' {g : Γ | g • w = v}).Finite :=
    F.finite_toSet.biUnion (fun s _ => s.vertices.finite_toSet.biUnion
      (fun w _ => (finite_vertex_transporter w v).image _))
  apply hf.subset
  rintro t ⟨hv, s, hs, g, rfl⟩
  obtain ⟨w, hw, he⟩ := Finset.mem_image.mp hv
  exact Set.mem_iUnion.mpr ⟨s, Set.mem_iUnion.mpr ⟨hs,
    Set.mem_iUnion.mpr ⟨w, Set.mem_iUnion.mpr ⟨hw, ⟨g, he, rfl⟩⟩⟩⟩⟩


/-- Any finite simplex containing the active support represents the same point. -/
theorem mem_coordinates_of_support_subset (x : LabeledOrbitRealization Γ)
    (t : LabeledOrbitSimplex Γ) (ht : (supportSimplex x).vertices ⊆ t.vertices) :
    x.val ∈ LabeledSimplexCoordinates Γ t := by
  classical
  refine ⟨x.property.choose_spec.1, ?_, ?_⟩
  · intro v hv
    by_contra hn
    exact hv (ht ((mem_supportSimplex x v).mpr hn))
  · rw [← (mem_coordinates_supportSimplex x).2.2]
    symm
    apply Finset.sum_subset ht
    intro v _ hv
    simpa using hv

/-- The nonzero-coordinate region lies in finitely many compact orbit charts. -/
theorem exists_compact_coordinate_container (F : Finset (LabeledOrbitSimplex Γ))
    (v : LabeledOrbitVertex Γ) :
    ∃ K : Set (OrbitFaceSpace F), IsCompact K ∧
      {y | y.val.val v ≠ 0} ⊆ K := by
    classical
    let Q : Set (LabeledOrbitSimplex Γ) :=
      {t | v ∈ t.vertices ∧ ∃ s ∈ F, ∃ g : Γ, g • s = t}
    have hQ : Q.Finite := finite_translated_charts_containing F v
    let : Finite Q := hQ.to_subtype
    have ha (t : Q) : t.val ∈ LabeledOrbitSimplex.orbitFaces F := by
      obtain ⟨_, s, hs, g, he⟩ := t.property
      exact ⟨s, hs, g, he ▸ Finset.Subset.refl _⟩
    let K : Set (OrbitFaceSpace F) := ⋃ t : Q, Set.range (orbitFaceChart t.val (ha t))
    have hK : IsCompact K := isCompact_iUnion (fun t => isCompact_range_orbitFaceChart _ (ha t))
    let U : Set (OrbitFaceSpace F) := {y | y.val.val v ≠ 0}
    have hUK : U ⊆ K := by
      intro y hy
      obtain ⟨s, hs, g, hg⟩ := y.property
      have hv' : v ∈ (g • s).vertices := hg ((mem_supportSimplex y.val v).mpr hy)
      let t : Q := ⟨g • s, hv', s, hs, g, rfl⟩
      refine Set.mem_iUnion.mpr ⟨t, ?_⟩
      refine ⟨⟨y.val.val, mem_coordinates_of_support_subset y.val (g • s) hg⟩, ?_⟩
      apply Subtype.ext
      rfl
    exact ⟨K, hK, hUK⟩

/-- Finitely many orbit charts give a compact neighborhood at every point. -/
instance weaklyLocallyCompact_orbitFaceSpace (F : Finset (LabeledOrbitSimplex Γ)) :
    WeaklyLocallyCompactSpace (OrbitFaceSpace F) where
  exists_compact_mem_nhds x := by
    obtain ⟨v, hv⟩ := exists_nonzero x.val
    obtain ⟨K, hK, hUK⟩ := exists_compact_coordinate_container F v
    have ho : IsOpen {y : OrbitFaceSpace F | y.val.val v ≠ 0} :=
      (isClosed_eq ((continuous_coordinate v).comp continuous_subtype_val) continuous_const).isOpen_compl
    exact ⟨K, hK, Filter.mem_of_superset (ho.mem_nhds hv) hUK⟩


instance locallyCompact_orbitFaceSpace (F : Finset (LabeledOrbitSimplex Γ)) :
    LocallyCompactSpace (OrbitFaceSpace F) := inferInstance

/-- Compact subspaces embed by coordinates into a countable real product. -/
theorem compact_secondCountable [Countable Γ] {F : Finset (LabeledOrbitSimplex Γ)}
    {K : Set (OrbitFaceSpace F)} (hK : IsCompact K) : SecondCountableTopology K := by
  let : CompactSpace K := isCompact_iff_compactSpace.mp hK
  have hc : Continuous (fun x : K => x.val.val.val) :=
    continuous_coordinates.comp (continuous_subtype_val.comp continuous_subtype_val)
  have hi : Function.Injective (fun x : K => x.val.val.val) := by
    intro x y h
    apply Subtype.ext
    apply Subtype.ext
    exact Subtype.ext h
  exact (hc.isClosedEmbedding hi).isEmbedding.secondCountableTopology

/-- Countably many coordinate neighborhoods, each inside a compact metrizable
subspace, make every finite-orbit subcomplex second countable. -/
instance secondCountable_orbitFaceSpace [Countable Γ]
    (F : Finset (LabeledOrbitSimplex Γ)) : SecondCountableTopology (OrbitFaceSpace F) := by
  let U (v : LabeledOrbitVertex Γ) : Set (OrbitFaceSpace F) := {y | y.val.val v ≠ 0}
  let hsc (v : LabeledOrbitVertex Γ) : SecondCountableTopology (U v) := by
    obtain ⟨K, hK, hUK⟩ := exists_compact_coordinate_container F v
    let : SecondCountableTopology K := compact_secondCountable hK
    exact (Topology.IsEmbedding.inclusion hUK).secondCountableTopology
  apply @TopologicalSpace.secondCountableTopology_of_countable_cover
    (OrbitFaceSpace F) _ (LabeledOrbitVertex Γ) _ U hsc (fun v => (isClosed_eq
      ((continuous_coordinate v).comp continuous_subtype_val) continuous_const).isOpen_compl)
  apply Set.eq_univ_of_forall
  intro x
  obtain ⟨v, hv⟩ := exists_nonzero x.val
  exact Set.mem_iUnion.mpr ⟨v, hv⟩


/-- Every face-closed collection is closed in the weak realization topology. -/
theorem isClosed_orbitFaceSpace (F : Finset (LabeledOrbitSimplex Γ)) :
    IsClosed {x : LabeledOrbitRealization Γ |
      supportSimplex x ∈ LabeledOrbitSimplex.orbitFaces F} := by
  classical
  apply (isClosed_iff _).mpr
  intro s
  let Q : Set (LabeledOrbitSimplex Γ) :=
    {t | t ∈ LabeledOrbitSimplex.orbitFaces F ∧ t.vertices ⊆ s.vertices}
  have hQ : Q.Finite :=
    (LabeledOrbitSimplex.finite_faceRepresentatives {s}).subset
      (fun t ht => ⟨s, by simp, ht.2⟩)
  let C (t : LabeledOrbitSimplex Γ) : Set (LabeledSimplexCoordinates Γ s) :=
    {w | ∀ v ∈ s.vertices, v ∉ t.vertices → w.val v = 0}
  have hc (t : LabeledOrbitSimplex Γ) : IsClosed (C t) := by
    simp only [C, Set.ofPred_forall]
    exact isClosed_iInter (fun v => isClosed_iInter (fun _ => isClosed_iInter (fun _ =>
      isClosed_eq ((continuous_apply v).comp continuous_subtype_val) continuous_const)))
  have he : (chart s) ⁻¹' {x | supportSimplex x ∈ LabeledOrbitSimplex.orbitFaces F} =
      ⋃ t ∈ Q, C t := by
    ext w
    constructor
    · intro hw
      refine Set.mem_iUnion.mpr ⟨supportSimplex (chart s w),
        Set.mem_iUnion.mpr ⟨⟨hw, support_chart_subset s w⟩, ?_⟩⟩
      intro v _ hv
      exact not_not.mp (fun hn => hv ((mem_supportSimplex (chart s w) v).mpr hn))
    · intro hw
      obtain ⟨t, ht, hwt⟩ := Set.mem_iUnion₂.mp hw
      apply LabeledOrbitSimplex.orbitFaces_downward ht.1
      intro v hv
      by_contra hn
      have hv' := support_chart_subset s w hv
      exact ((mem_supportSimplex (chart s w) v).mp hv) (hwt v hv' hn)
  rw [he]
  exact hQ.isClosed_biUnion (fun t _ => hc t)


/-- The canonical support simplex is equivariant. -/
theorem supportSimplex_smul (g : Γ) (x : LabeledOrbitRealization Γ) :
    supportSimplex (g • x) = g • supportSimplex x := by
  classical
  apply LabeledOrbitSimplex.ext
  apply Finset.ext
  intro v
  rw [mem_supportSimplex]
  change x.val (g⁻¹ • v) ≠ 0 ↔
    v ∈ (supportSimplex x).vertices.image (fun w => g • w)
  constructor
  · intro hv
    exact Finset.mem_image.mpr ⟨g⁻¹ • v, (mem_supportSimplex x _).mpr hv, by simp⟩
  · intro hv
    obtain ⟨w, hw, rfl⟩ := Finset.mem_image.mp hv
    simpa using (mem_supportSimplex x w).mp hw

instance (F : Finset (LabeledOrbitSimplex Γ)) : MulAction Γ (OrbitFaceSpace F) where
  smul g x := ⟨g • x.val, by
    rw [supportSimplex_smul]
    exact LabeledOrbitSimplex.orbitFaces_smul x.property g⟩
  one_smul x := Subtype.ext (one_smul Γ x.val)
  mul_smul g h x := Subtype.ext (mul_smul g h x.val)

instance (F : Finset (LabeledOrbitSimplex Γ)) : ContinuousConstSMul Γ (OrbitFaceSpace F) where
  continuous_const_smul g :=
    ((continuous_smul g).comp continuous_subtype_val).subtype_mk _


/-- A finite family of generating charts is a compact orbit-covering set. -/
theorem exists_compact_orbit_cover (F : Finset (LabeledOrbitSimplex Γ)) :
    ∃ K : Set (OrbitFaceSpace F), IsCompact K ∧ ∀ x, ∃ g : Γ, g • x ∈ K := by
  classical
  have ha (s : ↥(F : Set (LabeledOrbitSimplex Γ))) :
      s.val ∈ LabeledOrbitSimplex.orbitFaces F :=
    ⟨s.val, s.property, 1, by simp⟩
  let K : Set (OrbitFaceSpace F) := ⋃ s : ↥(F : Set (LabeledOrbitSimplex Γ)),
    Set.range (orbitFaceChart s.val (ha s))
  refine ⟨K, isCompact_iUnion (fun s => isCompact_range_orbitFaceChart _ (ha s)), ?_⟩
  intro x
  obtain ⟨s, hs, g, hg⟩ := x.property
  refine ⟨g⁻¹, Set.mem_iUnion.mpr ⟨⟨s, hs⟩, ?_⟩⟩
  have hc := (translateCoordinates g⁻¹ (g • s)
    ⟨x.val.val, mem_coordinates_of_support_subset x.val (g • s) hg⟩).property
  have he : (g • s).translate g⁻¹ = s := inv_smul_smul g s
  change (fun v => x.val.val ((g⁻¹)⁻¹ • v)) ∈
    LabeledSimplexCoordinates Γ ((g • s).translate g⁻¹) at hc
  rw [he] at hc
  refine ⟨⟨(g⁻¹ • x.val).val, hc⟩, ?_⟩
  apply Subtype.ext
  rfl


/-- Compact transporters remain finite on each invariant finite-orbit subspace. -/
theorem properlyDiscontinuous_orbitFaceSpace (F : Finset (LabeledOrbitSimplex Γ)) :
    ProperlyDiscontinuousSMul Γ (OrbitFaceSpace F) := by
  apply properlyDiscontinuousSMul_iff.mpr
  intro K L hK hL
  apply (finite_compact_transporter (hK.image continuous_subtype_val)
    (hL.image continuous_subtype_val)).subset
  intro g hg
  obtain ⟨y, hy, hyL⟩ := hg
  obtain ⟨x, hx, rfl⟩ := hy
  exact ⟨(g • x).val, ⟨x.val, ⟨x, hx, rfl⟩, rfl⟩, ⟨g • x, hyL, rfl⟩⟩

/-- For discrete groups the restricted finite-orbit action is proper. -/
theorem proper_orbitFaceSpace [TopologicalSpace Γ] [DiscreteTopology Γ]
    (F : Finset (LabeledOrbitSimplex Γ)) : ProperSMul Γ (OrbitFaceSpace F) :=
  properlyDiscontinuousSMul_iff_properSMul.mp (properlyDiscontinuous_orbitFaceSpace F)

end BC4lean.ProperActions.LabeledOrbitRealization
