import BC4lean.ModuleTensorPositivity
import BC4lean.ModuleTensorAction

/-! # The actual null space of the balanced tensor form

Finite pure-tensor expressions for two tensors can be combined into a shared
first-factor family. The actual amplified Gram matrix lies in the genuine
finite cone generated by matrix squares, whose pairings are finite sums of
inner products in F. A zero self-pairing
forces every transformed F-vector to vanish, proving the full radical property.
-/

noncomputable section
namespace BC4lean.KKTheory

open scoped TensorProduct InnerProductSpace
open CStarModule

variable {B C E F : Type*} [NonUnitalCStarAlgebra B] [NonUnitalCStarAlgebra C]
  [PartialOrder B] [StarOrderedRing B] [PartialOrder C] [StarOrderedRing C]
  [NormedAddCommGroup E] [NormedSpace ℂ E] [SMul Bᵐᵒᵖ E] [CStarModule Bᵐᵒᵖ E]
  [NormedAddCommGroup F] [NormedSpace ℂ F] [SMul Cᵐᵒᵖ F] [CStarModule Cᵐᵒᵖ F]
  [CompleteSpace E] [CompleteSpace F]

omit [PartialOrder B] [CStarModule Bᵐᵒᵖ E]
  [StarOrderedRing B] [StarOrderedRing C] [CompleteSpace E] [CompleteSpace F] in
/-- Every actual balanced tensor has a finite elementary expression. -/
theorem moduleTensor_exists_sum_mk
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) (u : BalancedModuleTensor (E := E) φ) :
    ∃ (k : ℕ) (x : Fin k → E) (y : Fin k → F), u = ∑ i, moduleTensorMk φ (x i) (y i) := by
  induction u using Submodule.Quotient.induction_on with
  | H u =>
    obtain ⟨k, x, y, rfl⟩ := TensorProduct.exists_sum_tmul_eq u
    exact ⟨k, x, y, by simp only [moduleTensorMk_apply, ← map_sum]; rfl⟩

/-- Zero self-pairing implies vanishing against any sum from the same finite
first-factor family. -/
theorem moduleTensorInner_sum_mk_eq_zero_of_self {n : Type*} [Fintype n]
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) (x : n → E) (y z : n → F)
    (hy : moduleTensorInner φ (∑ i, moduleTensorMk φ (x i) (y i))
      (∑ i, moduleTensorMk φ (x i) (y i)) = 0) :
    moduleTensorInner φ (∑ i, moduleTensorMk φ (x i) (y i))
      (∑ i, moduleTensorMk φ (x i) (z i)) = 0 := by
  let : PartialOrder (AdjointableMap C F F) := CStarAlgebra.spectralOrder _
  let : StarOrderedRing (AdjointableMap C F F) := CStarAlgebra.spectralOrderedRing _
  rw [moduleTensorInner_sum_mk_eq_matrix] at hy ⊢
  exact moduleMatrixPairing_eq_zero_of_quadratic _
    (map_nonneg (CStarMatrix.mapₙₐ φ) (moduleGramMatrix_nonneg x)) y z hy

/-- A tensor with zero inner square lies in the full radical of the actual form. -/
theorem moduleTensorInner_eq_zero_of_self
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (u v : BalancedModuleTensor (E := E) φ) (hu : moduleTensorInner φ u u = 0) :
    moduleTensorInner φ u v = 0 := by
  obtain ⟨k, x, y, hx⟩ := moduleTensor_exists_sum_mk φ u
  obtain ⟨l, x', z, hx'⟩ := moduleTensor_exists_sum_mk φ v
  let w : Fin (k + l) → E := Fin.addCases x x'
  let a : Fin (k + l) → F := Fin.addCases y (fun _ => 0)
  let b : Fin (k + l) → F := Fin.addCases (fun _ => 0) z
  have ha : (∑ i, moduleTensorMk φ (w i) (a i)) = u := by
    rw [Fin.sum_univ_add]
    simpa only [w, a, Fin.addCases_left, Fin.addCases_right, map_zero,
      Finset.sum_const_zero, add_zero] using hx.symm
  have hb : (∑ i, moduleTensorMk φ (w i) (b i)) = v := by
    rw [Fin.sum_univ_add]
    simpa only [w, b, Fin.addCases_left, Fin.addCases_right, map_zero,
      Finset.sum_const_zero, zero_add] using hx'.symm
  rw [← ha, ← hb]
  apply moduleTensorInner_sum_mk_eq_zero_of_self φ w a b
  simpa only [ha] using hu

/-- The tensor null space is the actual linear kernel of the descended form. -/
def moduleTensorNull (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) :
    Submodule ℂ (BalancedModuleTensor (E := E) φ) := LinearMap.ker (moduleTensorInner φ)

/-- Kernel membership is equivalent to the original coefficient inner square
vanishing. This equivalence is proved, not built into the quotient. -/
theorem mem_moduleTensorNull_iff
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) (u : BalancedModuleTensor (E := E) φ) :
    u ∈ moduleTensorNull φ ↔ moduleTensorInner φ u u = 0 := by
  constructor
  · intro h
    exact congrArg (fun f => f u) h
  · intro h
    apply LinearMap.ext
    intro v
    exact moduleTensorInner_eq_zero_of_self φ u v h

/-- The null space is invariant under the actual right coefficient action. -/
theorem moduleTensorNull_smul_mem
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) (a : Cᵐᵒᵖ)
    {u : BalancedModuleTensor (E := E) φ} (hu : u ∈ moduleTensorNull φ) :
    a • u ∈ moduleTensorNull φ := by
  rw [mem_moduleTensorNull_iff] at hu ⊢
  rw [moduleTensorInner_op_smul_left, moduleTensorInner_op_smul_right, hu,
    mul_zero, zero_mul]

end BC4lean.KKTheory
