import BC4lean.ModuleTensorInner
import BC4lean.ModuleGramMatrix
import Mathlib.LinearAlgebra.TensorProduct.Finiteness

/-! # Positivity of the actual balanced tensor form

Finite Gram matrices are positive in the actual matrix C*-algebra.  The
entrywise amplification of the coefficient star-homomorphism preserves their
positivity. The genuine positive matrix cone is generated by actual R* R
squares, each giving a sum of actual inner squares in the second module.  Every algebraic
tensor is a finite sum, so this proves positivity on the constructed quotient.
No positivity axiom for a proposed tensor product is used.
-/

noncomputable section
namespace BC4lean.KKTheory

open scoped InnerProductSpace TensorProduct
open CStarModule

variable {C F n ι : Type*} [NonUnitalCStarAlgebra C] [PartialOrder C]
  [NormedAddCommGroup F] [NormedSpace ℂ F] [SMul Cᵐᵒᵖ F] [CStarModule Cᵐᵒᵖ F]

/-- Finite sums of adjointable maps act as the corresponding finite vector sum. -/
theorem moduleAdjointable_sum_apply (s : Finset ι) (T : ι → AdjointableMap C F F) (y : F) :
    (∑ i ∈ s, T i) y = ∑ i ∈ s, T i y := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
    simp only [Finset.sum_insert hi, AdjointableMap.coe_add_apply, ih]

variable [Fintype n]

/-- The coefficient-valued pairing of a matrix of adjointable maps. -/
def moduleMatrixPairing (M : CStarMatrix n n (AdjointableMap C F F))
    (y z : n → F) : Cᵐᵒᵖ := ∑ i, ∑ j, ⟪y i, M i j (z j)⟫_(Cᵐᵒᵖ)

/-- The coefficient-valued quadratic form of a matrix of adjointable maps. -/
def moduleMatrixQuadratic (M : CStarMatrix n n (AdjointableMap C F F)) (y : n → F) : Cᵐᵒᵖ :=
  moduleMatrixPairing M y y

/-- A matrix square gives a sum of actual second-module inner squares. -/
theorem moduleMatrixPairing_star_mul (R : CStarMatrix n n (AdjointableMap C F F))
    (y z : n → F) :
    moduleMatrixPairing (star R * R) y z =
      ∑ k, ⟪∑ i, R k i (y i), ∑ j, R k j (z j)⟫_(Cᵐᵒᵖ) := by
  classical
  have hinner (T U : AdjointableMap C F F) (v w : F) :
      ⟪v, (star T * U) w⟫_(Cᵐᵒᵖ) = ⟪T v, U w⟫_(Cᵐᵒᵖ) := by
    exact (T.adjoint_identity v (U w)).symm
  simp only [moduleMatrixPairing, CStarMatrix.mul_apply, CStarMatrix.star_apply,
    moduleAdjointable_sum_apply, inner_sum_right, hinner, inner_sum_left]
  calc
    (∑ i, ∑ j, ∑ k, ⟪R k i (y i), R k j (z j)⟫_(Cᵐᵒᵖ)) =
        ∑ i, ∑ k, ∑ j, ⟪R k i (y i), R k j (z j)⟫_(Cᵐᵒᵖ) := by
      apply Finset.sum_congr rfl
      intro i _
      rw [Finset.sum_comm]
    _ = ∑ k, ∑ i, ∑ j, ⟪R k i (y i), R k j (z j)⟫_(Cᵐᵒᵖ) := Finset.sum_comm
    _ = ∑ k, ∑ j, ∑ i, ⟪R k i (y i), R k j (z j)⟫_(Cᵐᵒᵖ) := by
      apply Finset.sum_congr rfl
      intro k _
      rw [Finset.sum_comm]

/-- Specialize the matrix-square pairing to its quadratic form. -/
theorem moduleMatrixQuadratic_star_mul (R : CStarMatrix n n (AdjointableMap C F F))
    (y : n → F) :
    moduleMatrixQuadratic (star R * R) y =
      ∑ k, ⟪∑ i, R k i (y i), ∑ j, R k j (y j)⟫_(Cᵐᵒᵖ) :=
  moduleMatrixPairing_star_mul R y y

variable [StarOrderedRing C] [CompleteSpace F]

local instance : PartialOrder (AdjointableMap C F F) := CStarAlgebra.spectralOrder _
local instance : StarOrderedRing (AdjointableMap C F F) := CStarAlgebra.spectralOrderedRing _

omit [StarOrderedRing C] [CompleteSpace F] in
/-- The actual matrix pairing is additive in its coefficient matrix. -/
theorem moduleMatrixPairing_add
    (M N : CStarMatrix n n (AdjointableMap C F F)) (y z : n → F) :
    moduleMatrixPairing (M + N) y z = moduleMatrixPairing M y z + moduleMatrixPairing N y z := by
  classical
  simp only [moduleMatrixPairing, CStarMatrix.add_apply, AdjointableMap.coe_add_apply,
    CStarModule.inner_add_right, Finset.sum_add_distrib]

omit [StarOrderedRing C] [CompleteSpace F] in
/-- Zero coefficient matrices give zero actual pairings. -/
@[simp] theorem moduleMatrixPairing_zero (y z : n → F) :
    moduleMatrixPairing (0 : CStarMatrix n n (AdjointableMap C F F)) y z = 0 := by
  simp [moduleMatrixPairing]

/-- A positive matrix has a positive actual quadratic pairing. The actual
star-ordered matrix cone consists of finite sums of matrix squares. -/
theorem moduleMatrixQuadratic_nonneg
    (M : CStarMatrix n n (AdjointableMap C F F))
    (hM : 0 ≤ M) (y : n → F) : 0 ≤ moduleMatrixQuadratic M y := by
  rw [StarOrderedRing.nonneg_iff] at hM
  induction hM using AddSubmonoid.closure_induction with
  | mem M hM =>
    obtain ⟨R, rfl⟩ := hM
    rw [moduleMatrixQuadratic_star_mul]
    exact Finset.sum_nonneg fun _ _ => CStarModule.inner_self_nonneg
  | zero => simp [moduleMatrixQuadratic]
  | add M N hM hN ihM ihN =>
    simpa only [moduleMatrixQuadratic, moduleMatrixPairing_add] using add_nonneg ihM ihN

/-- A zero quadratic vector is in the radical of a positive matrix pairing.
Each actual matrix square gives finite F-vectors. Positive additivity extends
the result to the genuine matrix cone. -/
theorem moduleMatrixPairing_eq_zero_of_quadratic
    (M : CStarMatrix n n (AdjointableMap C F F)) (hM : 0 ≤ M)
    (y z : n → F) (hy : moduleMatrixQuadratic M y = 0) :
    moduleMatrixPairing M y z = 0 := by
  classical
  rw [StarOrderedRing.nonneg_iff] at hM
  induction hM using AddSubmonoid.closure_induction with
  | mem M hM =>
    obtain ⟨R, rfl⟩ := hM
    have hsum : (∑ k, ⟪∑ i, R k i (y i), ∑ j, R k j (y j)⟫_(Cᵐᵒᵖ)) = 0 := by
      rw [moduleMatrixQuadratic_star_mul] at hy
      exact hy
    have hzero (k : n) : (∑ i, R k i (y i)) = 0 := by
      apply (CStarModule.inner_self (A := Cᵐᵒᵖ)).mp
      apply le_antisymm _ CStarModule.inner_self_nonneg
      have hle := Finset.single_le_sum
        (f := fun k => ⟪∑ i, R k i (y i), ∑ i, R k i (y i)⟫_(Cᵐᵒᵖ))
        (fun _ _ => CStarModule.inner_self_nonneg) (Finset.mem_univ k)
      exact hle.trans_eq hsum
    rw [moduleMatrixPairing_star_mul]
    simp only [hzero, CStarModule.inner_zero_left, Finset.sum_const_zero]
  | zero => exact moduleMatrixPairing_zero y z
  | add M N hM hN ihM ihN =>
    have hMpos : 0 ≤ M := StarOrderedRing.nonneg_iff.mpr hM
    have hNpos : 0 ≤ N := StarOrderedRing.nonneg_iff.mpr hN
    have hM0 : moduleMatrixQuadratic M y = 0 := by
      apply le_antisymm _ (moduleMatrixQuadratic_nonneg M hMpos y)
      have hle : moduleMatrixQuadratic M y ≤ moduleMatrixQuadratic M y + moduleMatrixQuadratic N y :=
        le_add_of_nonneg_right (moduleMatrixQuadratic_nonneg N hNpos y)
      apply hle.trans_eq
      simpa only [moduleMatrixQuadratic, moduleMatrixPairing_add] using hy
    have hN0 : moduleMatrixQuadratic N y = 0 := by
      apply le_antisymm _ (moduleMatrixQuadratic_nonneg N hNpos y)
      have hle : moduleMatrixQuadratic N y ≤ moduleMatrixQuadratic M y + moduleMatrixQuadratic N y :=
        le_add_of_nonneg_left (moduleMatrixQuadratic_nonneg M hMpos y)
      apply hle.trans_eq
      simpa only [moduleMatrixQuadratic, moduleMatrixPairing_add] using hy
    rw [moduleMatrixPairing_add, ihM hM0, ihN hN0, add_zero]

variable {B E : Type*} [NonUnitalCStarAlgebra B] [PartialOrder B] [StarOrderedRing B]
  [NormedAddCommGroup E] [NormedSpace ℂ E] [SMul Bᵐᵒᵖ E] [CStarModule Bᵐᵒᵖ E]
  [CompleteSpace E]

omit [StarOrderedRing C] [CompleteSpace F] [StarOrderedRing B] [CompleteSpace E] in
/-- Finite tensor sums with the same first-factor family are paired by its
actual amplified Gram matrix. -/
theorem moduleTensorInner_sum_mk_eq_matrix
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) (x : n → E) (y z : n → F) :
    moduleTensorInner φ (∑ i, moduleTensorMk φ (x i) (y i))
      (∑ i, moduleTensorMk φ (x i) (z i)) =
        moduleMatrixPairing (CStarMatrix.mapₙₐ φ (moduleGramMatrix x)) y z := by
  simp only [map_sum, LinearMap.sum_apply, moduleTensorInner_mk_mk]
  rw [Finset.sum_comm]
  rfl

/-- Positivity of the entire inner square of an arbitrary finite sum of elementary tensors. -/
theorem moduleTensorInner_sum_mk_self_nonneg
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F) (x : n → E) (y : n → F) :
    0 ≤ moduleTensorInner φ (∑ i, moduleTensorMk φ (x i) (y i))
      (∑ i, moduleTensorMk φ (x i) (y i)) := by
  have hM : 0 ≤ CStarMatrix.mapₙₐ φ (moduleGramMatrix x) :=
    map_nonneg (CStarMatrix.mapₙₐ φ) (moduleGramMatrix_nonneg x)
  have h := moduleMatrixQuadratic_nonneg _ hM y
  rw [moduleTensorInner_sum_mk_eq_matrix]
  exact h

/-- The coefficient-valued form is positive on every actual balanced algebraic tensor. -/
theorem moduleTensorInner_self_nonneg
    (φ : B →⋆ₙₐ[ℂ] AdjointableMap C F F)
    (u : BalancedModuleTensor (E := E) φ) : 0 ≤ moduleTensorInner φ u u := by
  induction u using Submodule.Quotient.induction_on with
  | H u =>
    obtain ⟨k, x, y, rfl⟩ := TensorProduct.exists_sum_tmul_eq u
    have h := moduleTensorInner_sum_mk_self_nonneg φ x y
    change 0 ≤ moduleTensorInner φ ((moduleTensorRelations φ).mkQ (∑ i, x i ⊗ₜ[ℂ] y i))
      ((moduleTensorRelations φ).mkQ (∑ i, x i ⊗ₜ[ℂ] y i))
    simpa only [moduleTensorMk_apply, map_sum] using h

end BC4lean.KKTheory
