import BC4lean.IntegratedRepresentation
import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap

/-! # The concrete reduced group C⋆-algebra

The underlying set is the operator-norm closure of the integrated regular image.
The C⋆-algebra structure is inherited from bounded operators on ℓ²(Γ).
-/

noncomputable section

namespace BC4lean

variable (Γ : Type*) [Group Γ]

/-- The closed star subalgebra generated by the integrated regular image. -/
def reducedAlgebra : StarSubalgebra ℂ (L2Group Γ →L[ℂ] L2Group Γ) :=
  (integratedStarHom (Γ := Γ)).range.topologicalClosure

/-- The concrete reduced group C⋆-algebra. -/
abbrev ReducedGroupCStar := ↥(reducedAlgebra Γ)

variable {Γ}

theorem reducedAlgebra_coe_eq_closure_range :
    (reducedAlgebra Γ : Set (L2Group Γ →L[ℂ] L2Group Γ)) =
      closure (Set.range (integratedRepresentation (Γ := Γ))) := rfl

theorem reducedAlgebra_isClosed :
    IsClosed (reducedAlgebra Γ : Set (L2Group Γ →L[ℂ] L2Group Γ)) :=
  isClosed_closure

instance reducedGroupCStarAlgebra : CStarAlgebra (ReducedGroupCStar Γ) :=
  StarSubalgebra.cstarAlgebra _ (h_closed := reducedAlgebra_isClosed)

/-- The identity regular operator has norm one, also for the trivial group. -/
instance regularOperatorsNormOne : NormOneClass (L2Group Γ →L[ℂ] L2Group Γ) where
  norm_one := by
    simpa only [regularOperator_one] using norm_regularOperator (1 : Γ)

instance reducedGroupCStarNormOne : NormOneClass (ReducedGroupCStar Γ) where
  norm_one := by
    change ‖(1 : L2Group Γ →L[ℂ] L2Group Γ)‖ = 1
    exact norm_one

/-- The canonical faithful star homomorphism with dense image. -/
def integratedToReduced : GroupAlgebra Γ →⋆ₐ[ℂ] ReducedGroupCStar Γ :=
  integratedStarHom.codRestrict (reducedAlgebra Γ)
    (fun a => subset_closure ⟨a, rfl⟩)

@[simp] theorem integratedToReduced_coe (a : GroupAlgebra Γ) :
    (integratedToReduced a : L2Group Γ →L[ℂ] L2Group Γ) =
      integratedRepresentation a := rfl

theorem integratedToReduced_injective :
    Function.Injective (integratedToReduced (Γ := Γ)) := by
  intro a b h
  exact integratedRepresentation_injective (congrArg Subtype.val h)

@[simp] theorem norm_integratedToReduced (a : GroupAlgebra Γ) :
    ‖integratedToReduced a‖ = reducedNorm a := rfl

theorem denseRange_integratedToReduced :
    DenseRange (integratedToReduced (Γ := Γ)) := by
  intro T
  rw [closure_subtype, ← Set.range_comp]
  change (T : L2Group Γ →L[ℂ] L2Group Γ) ∈
    closure (Set.range (integratedRepresentation (Γ := Γ)))
  rw [← reducedAlgebra_coe_eq_closure_range]
  exact T.property

theorem regularOperator_mem_reducedAlgebra (g : Γ) :
    regularOperator g ∈ reducedAlgebra Γ :=
  subset_closure ⟨GroupAlgebra.delta g, integratedRepresentation_delta g⟩

theorem reducedAlgebra_coe_eq_closure_span :
    (reducedAlgebra Γ : Set (L2Group Γ →L[ℂ] L2Group Γ)) =
      closure (Submodule.span ℂ (Set.range (regularOperator (Γ := Γ))) :
        Set (L2Group Γ →L[ℂ] L2Group Γ)) := by
  rw [← integratedRepresentation_range]
  rfl

/-- Minimality among closed complex star subalgebras containing all regular operators. -/
theorem reducedAlgebra_minimal (S : StarSubalgebra ℂ (L2Group Γ →L[ℂ] L2Group Γ))
    (hS : IsClosed (S : Set (L2Group Γ →L[ℂ] L2Group Γ)))
    (h : ∀ g : Γ, regularOperator g ∈ S) : reducedAlgebra Γ ≤ S := by
  apply StarSubalgebra.topologicalClosure_minimal _ hS
  rintro T ⟨a, rfl⟩
  change integratedRepresentation a ∈ S
  induction a using MonoidAlgebra.induction_linear with
  | zero => simp
  | add a b ha hb =>
    rw [map_add]
    exact S.add_mem ha hb
  | single g z => simpa only [integratedRepresentation_single] using S.smul_mem (h g) z

/-- Countability is needed here, but not for the C⋆-algebra construction. -/
instance reducedGroupCStarSeparable [Countable Γ] : TopologicalSpace.SeparableSpace (ReducedGroupCStar Γ) := by
  apply TopologicalSpace.IsSeparable.separableSpace
  rw [reducedAlgebra_coe_eq_closure_span]
  exact ((Set.countable_range (regularOperator (Γ := Γ))).isSeparable.span (R := ℂ)).closure

end BC4lean
