name = "BC4lean"
defaultTargets = ["BC4lean"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.1"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
[[lean_lib]]
name = "BC4lean"
